# Generated by Django 5.2.7 on 2025-11-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Use image URL instead of uploading', max_length=500, null=True),
        ),
    ]
