# Generated by Django 5.2.7 on 2025-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+918750971212', help_text='Phone number for WhatsApp and contact (format: +918750971212)', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number (if different from phone number). Leave blank to use phone_number.', max_length=20, null=True)),
                ('email', models.EmailField(default='inoxflex10@gmail.com', help_text='Contact email address', max_length=254)),
                ('address', models.TextField(default='417/21, Nehru Park, Old DSP Street, Bahadurgarh', help_text='Office address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
