# Generated by Django 5.2.7 on 2025-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(help_text='e.g., Founder & Director, CEO', max_length=100)),
                ('description', models.TextField(help_text='Brief description about the team member')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL', max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('status', models.BooleanField(default=True, help_text='Show/hide this team member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'first_name'],
            },
        ),
    ]
