# Generated by Django 5.2.7 on 2025-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph Image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (recommended: 150-160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title (recommended: 50-60 characters)', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph Description (recommended: 200 characters)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph Image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph Title (recommended: 60-95 characters)', max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (recommended: 150-160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma-separated)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title (recommended: 50-60 characters)', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Twitter Card Type', max_length=20),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter Card Description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter Card Image (1200x675px recommended)', null=True, upload_to='seo/twitter/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card Title', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph Image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (recommended: 150-160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title (recommended: 50-60 characters)', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_description',
            field=models.TextField(default='Leading manufacturer and exporter of Stainless Steel Corrugated Hoses, Hose Assemblies, Metallic Bellows, Expansion Joints, and Pipe Fittings.', help_text='Default SEO Meta Description (recommended: 150-160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_keywords',
            field=models.CharField(default='stainless steel hoses, pipe fittings, corrugated hoses, expansion joints, metallic bellows', help_text='Default SEO Keywords (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(default='Inox Flex - Stainless Steel Hoses & Pipe Fittings', help_text='Default SEO Title for pages without specific SEO (recommended: 50-60 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image_default',
            field=models.ImageField(blank=True, help_text='Default Open Graph Image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Inox Flex', help_text='Site Name for Open Graph tags', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter Handle (e.g., @inoxflex) - without @ symbol', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph Image (1200x630px recommended)', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (recommended: 150-160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title (recommended: 50-60 characters)', max_length=70, null=True),
        ),
    ]
