# Generated by Django 5.2.7 on 2025-11-18 18:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_pagecontent_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add product specifications, technical details, or table data here. You can use HTML tables.', null=True),
        ),
    ]
